AWSTemplateFormatVersion: "2010-09-09"

Description: >
  A simple example of how to create an ecs task role with permissions to get env out of SSM

Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Join [ '-', [ !Ref 'AWS::StackName', 'service', 'policy' ] ]
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Action:
              - 'iam:PassRole'
              - 'ssm:DescribeParameters'
              - 'ssm:GetParametersByPath'
              Effect: Allow
              Resource: '*'            
            - Action: #see https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
              - 'ssm:GetParameter*'
              Effect: Allow
              Resource: 
                - !Sub "arn:aws:ssm:*:${AWS::AccountId}:parameter/*"               
            - Effect: Allow
              Action:
              - 'sns:Get*'
              Resource: '*'          

Outputs:
  TaskIamRoleArn:
    Description: The IAM role for ECS task
    Value: !Sub arn:aws:iam::${AWS::AccountId}:role/${EcsTaskRole}